config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :tasks, shallow: true do
      member do
        get :finish
        get :re_open
      end
    end
  end

  get 'users/:user_id/tasks', to: 'tasks#user_tasks', as: 'user_tasks'
  post 'users/:user_id/tasks', to: 'tasks#create_for_user'

  devise_for :users
  root 'pages#home'

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  include AASM

  belongs_to :assignee, class_name: 'User'
  belongs_to :list

  aasm column: 'status', whiny_transitions: false do
    state :incomplete, initial: true
    state :complete

    event :finish do
      transitions from: :incomplete, to: :complete
    end

    event :re_open do
      transitions from: :complete, to: :incomplete
    end
  end

  scope :ordered, -> { order('created_at DESC') }

  validates :title, presence: true
  validates :description, presence: true
  validates :assignee, presence: true
  validates :list, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :assigned_tasks, foreign_key: :assignee_id, class_name: 'Task'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_tasks_path(resource)
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    @title = 'Lists'
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @title = 'View List'
    @filter = params[:filter] || 'all'
    @tasks = if ['complete', 'incomplete'].include? @filter
      @list.tasks.send(@filter).ordered
    else
      @list.tasks.ordered
    end
  end

  # GET /lists/new
  def new
    @title = 'New List'
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    @title = 'Edit List'
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
    redirect_to lists_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:index, :new, :create]
  before_action :set_user, only: [:user_tasks, :create_for_user]
  before_action :set_task, only: [:show, :edit, :update, :destroy, :finish, :re_open]

  def index
    @title = 'Tasks'
    @tasks = @list.tasks.ordered
  end

  def user_tasks
    @title = 'Assigned Tasks'
    @filter = params[:filter] || 'incomplete'
    @tasks = if ['complete', 'all'].include? @filter
      @user.assigned_tasks.send(@filter).ordered
    else
      @user.assigned_tasks.incomplete.ordered
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @title = 'View Task'
  end

  def new
    @title = 'New Task'
    @task = @list.tasks.new
  end

  # GET /tasks/1/edit
  def edit
    @title = 'Edit Task'
  end

  def create
    @task = @list.tasks.new(task_params)
    @task.assignee = current_user unless @task.assignee.present?

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task.list, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task.list }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def create_for_user
    @task = @user.assigned_tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task.list, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task.list }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task.list, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task.list }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @list = @task.list
    @task.destroy
    respond_to do |format|
      format.html { redirect_to list_tasks_url(@list), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end


  # PATCH/PUT /tasks/1
  def finish
    @task.finish
    @task.save
    respond_to do |format|
      format.html { redirect_to @task, notice: 'Task was successfully completed.' }
      if @task.complete?
        format.json { render :show, status: :ok, location: @task }
      else
        format.json { render json: { error: 'Task could not be completed' }, status: :unprocessable_entity }
      end
    end
  end

# PATCH/PUT /tasks/1
  def re_open
    @task.re_open
    @task.save
    respond_to do |format|
      format.html { redirect_to @task, notice: 'Task was successfully completed.' }
      if @task.incomplete?
        format.json { render :show, status: :ok, location: @task }
      else
        format.json { render json: { error: 'Task could not be re-opened' }, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_list
      @list = List.find(params[:list_id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :assignee_id, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info alert-dismissable"
      when :success then "alert alert-success alert-dismissable"
      when :error then "alert alert-danger alert-dismissable"
      when :alert then "alert alert-warning alert-dismissable"
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def class_for_task_item(task)
    'complete-item' if task.complete?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || 'App' %> - TodoList</title>
  <meta charset="UTF-8">
  <meta name="google" content="notranslate">
  <meta http-equiv="Content-Language" content="en">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Todo List">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">
    <header>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <%= link_to 'Todo List', root_path, class: 'navbar-brand'%>
          <ul class="nav navbar-nav">
            <li class="nav-item <%= 'active' if params[:controller] == 'lists' %>">
              <%= link_to 'Lists', lists_path, class: 'nav-link' %>
            </li>
            <% if current_user.present? %>
              <li class="nav-item <%= 'active' if params[:controller] == 'tasks' %>">
                <%= link_to 'My Tasks', user_tasks_path(current_user), class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.present? %>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-log-out"></span> Logout
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to new_user_registration_path do %>
                  <span class="glyphicon glyphicon-user"></span> Sign Up
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_session_path do %>
                  <span class="glyphicon glyphicon-log-in"></span> Login
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <%= render partial: 'shared/flash_messages' %>

    <%= yield %>
  </div>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'List Name', to: :name %>
    <%= f.text_field :name, placeholder: 'Enter list name here...', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <h1>Editing List</h1>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <%= render 'form' %>
        <%= link_to 'Show', @list %> |
        <%= link_to 'Back', lists_path %>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <h1>Lists</h1>
        <%= link_to new_list_path do %>
          <span class="glyphicon glyphicon-plus"></span> <strong>Add New List</strong>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if @lists.present? %>
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          <table class="table table-responsive">
            <thead>
              <tr>
                <th>List Name</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @lists.each do |list| %>
                <tr>
                  <td><%= list.name %></td>
                  <td><%= link_to 'Go to Tasks', list %></td>
                  <td>
                    <%= link_to edit_list_path(list), class: 'action', data: { toggle: 'tooltip' }, title: 'Edit' do %>
                      <span class="glyphicon glyphicon-edit"></span>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to list, method: :delete, class: 'action remove-action', data: { confirm: 'Are you sure?', toggle: 'tooltip' }, title: 'Edit' do %>
                      <span class="glyphicon glyphicon-trash"></span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/lists/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <h1>New List</h1>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <%= render 'form' %>
        <%= link_to 'Back', lists_path %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="row page-header">
  <div class="col-sm-12">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h2><%= @list.name %></h2>
        <h3><%= @filter.capitalize %> Tasks</h3>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <ul id="task-filters">
          <%= link_to list_path(@list, filter: 'incomplete') do %>
            <li class="task-filter <%= 'active' if @filter == 'incomplete' %>">Incomplete Tasks</li>
          <% end %>
          <%= link_to list_path(@list, filter: 'complete') do %>
            <li class="task-filter <%= 'active' if @filter == 'complete' %>">Complete Tasks</li>
          <% end %>
          <%= link_to list_path(@list, filter: 'all') do %>
            <li class="task-filter <%= 'active' if @filter == 'all' %>">All Tasks</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="row">
      <div class="col-sm-12">
        <div class="add-btn-wrapper">
          <%= button_tag data: { toggle: 'modal', target: '#task-form-modal' }, class: 'add-task-btn btn btn-secondary' do %>
            <span class="glyphicon glyphicon-plus"></span> <strong>Add Task</strong>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <ul id="task-container" data-filter=<%= @filter %>>
          <%= render @tasks %>
        </ul>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'tasks/remote_form', locals: { task: @list.tasks.new } %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key.to_sym) %>">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= value %>
  </div>
<% end %>

app/views/tasks/_assignment_form.html.erb
<div id="task-form-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add New Task</h4>
      </div>
      <div class="modal-body">
        <%= form_for task, url: user_tasks_path(task.assignee), remote: true do |form| %>
          <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: 'Enter title here...', class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, placeholder: 'Enter description here...', maxlength: 500, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.label :list_id %>
            <%= form.collection_select :list_id, List.order(:name), :id, :name, { prompt: true },{ class: 'form-control', required: true } %>
          </div>
          <div class="form-group">
            <%= form.label :due_date %>
            <div class='input-group date' id='date-field-container'>
              <%= form.text_field :due_date, class: 'form-control' %>
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>

          <%= button_tag 'Create Task', class: 'btn btn-primary', id: 'task-submit-btn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_for [@list, @task].compact do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Enter title here...', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: 'Enter description here...', maxlength: 500, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :due_date %>
    <div class='input-group date' id='date-field-container'>
      <%= f.text_field :due_date, class: 'form-control' %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :assignee_id %>
    <%= f.collection_select :assignee_id, User.order(:email), :id, :email, { include_blank: true },{ class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :list_id %>
    <%= f.collection_select :list_id, List.order(:name), :id, :name, { include_blank: true },{ class: 'form-control', required: true } %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/_remote_form.html.erb
<div id="task-form-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add New Task</h4>
      </div>
      <div class="modal-body">
        <%= form_for [task.list, task], remote: true do |form| %>
          <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: 'Enter title here...', class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, placeholder: 'Enter description here...', maxlength: 500, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.label :assignee_id %>
            <%= form.collection_select :assignee_id, User.order(:email), :id, :email, { prompt: true }, { class: 'form-control' } %>
          </div>
          <div class="form-group">
            <%= form.label :due_date %>
            <div class='input-group date' id='date-field-container'>
              <%= form.text_field :due_date, class: 'form-control' %>
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
          <%= button_tag 'Create Task', class: 'btn btn-primary', id: 'task-submit-btn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<% if task.persisted? %>
  <li id="task-<%= task.id %>" class="task-item <%= class_for_task_item task %>">
    <div class="pull-right task-actions">
      <%= link_to task_path(task), class: 'action', data: { toggle: 'tooltip' }, title: 'Open' do %>
        <span class="glyphicon glyphicon glyphicon-new-window"></span>
      <% end %>

      <%= link_to edit_task_path(task), class: 'action', data: { toggle: 'tooltip' }, title: 'Edit' do %>
        <span class="glyphicon glyphicon-edit"></span>
      <% end %>

      <%= link_to task, class: 'remote-task-remove-link action remove-action', data: { toggle: 'tooltip' }, title: 'Delete', remote: true, method: :delete do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </div>
    <div class="task-header">
      <div class="checkbox pull-right">
        <%= check_box_tag 'complete', true, task.complete?, data: { id: task.id }, class: 'finish-btn' %>
      </div>
      <h3><%= task.title %></h3>
    </div>
    <hr />
    <p class="task-desc"><%= task.description %></p>
    <hr />
    <p class="task-assignee text-center"><strong>Assigned to:</strong> <%= task.assignee.try :email %></p>
    <hr />
    <div class="row task-footer">
      <div class="col-sm-6 text-center">
        List: <%= task.list.try(:name) %>
      </div>
      <div class="col-sm-6 text-center">
        Due: <%= task.due_date %>
      </div>
    </div>
  </li>
<% end %>

app/views/tasks/create.js.erb
<% if @task.errors.any? %>
  <% @task.errors.full_messages.each do |error| %>
    alert("<%= raw j error %>");
  <% end %>
<% else %>
  var container = $('#task-container');
  $('#task-form-modal').modal('hide');
  $('#new_task')[0].reset();
  if(container.data('filter') == 'complete') {
    window.location.href = '/lists/' + '<%= @task.list.id %>' + '?filter=all';
  } else {
    container.prepend("<%= j render @task %>");
  }
<% end %>

app/views/tasks/create_for_user.js.erb
<% if @task.errors.any? %>
  <% @task.errors.full_messages.each do |error| %>
    alert("<%= raw j error %>");
  <% end %>
<% else %>
  var container = $('#task-container');
  $('#task-form-modal').modal('hide');
  $('#new_task')[0].reset();
  if(container.data('filter') == 'complete') {
    window.location.href = '/lists/' + '<%= @task.list.id %>' + '?filter=all';
  } else {
    container.prepend("<%= j render @task %>");
  }
<% end %>

app/views/tasks/destroy.js.erb
$("#task-<%= @task.id %>").remove();
$('.container-fluid > header').after("<%= j render partial: 'shared/flash_messages', locals: { flash: {notice: 'Task has been deleted.'} } %>");
window.setTimeout(window.fade_alert, 3000)

app/views/tasks/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <h1>Editing Task</h1>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <%= render 'form' %>
        <%= link_to 'Back', task_path(@task) %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <h1><%= @list.try(:name) %></h1>
        <small>Tasks</small>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <table class="table table-responsive">
          <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th>Due date</th>
              <th>Assignee</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @tasks.each do |task| %>
              <tr>
                <td><%= task.title %></td>
                <td><%= task.description %></td>
                <td><%= task.due_date %></td>
                <td><%= task.assignee.try(:email) %></td>
                <td><%= link_to 'Show', task %></td>
                <td><%= link_to 'Edit', edit_task_path(task) %></td>
                <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'New Task', new_list_task_path(@list) %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <h1>New Task</h1>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <%= render 'form' %>
        <%= link_to 'Back', list_tasks_path(@list) %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="row page-header">
  <div class="col-sm-12">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h2><%= @task.title %></h2>
      </div>
    </div>

    <p>
      <strong>Description:</strong>
      <%= @task.description %>
    </p>

    <p>
      <strong>Due date:</strong>
      <%= @task.due_date %>
    </p>

    <p>
      <strong>Assignee:</strong>
      <%= @task.assignee.try(:email) %>
    </p>

    <%= link_to 'Edit', edit_task_path(@task) %> |
    <%= link_to 'Back', list_path(@task.list) %>

  </div>
</div>

app/views/tasks/user_tasks.html.erb
<div class="row page-header">
  <div class="col-sm-12">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h1>My Tasks</h1>
        <h2><%= @user.email %></h2>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <ul id="task-filters">
          <%= link_to user_tasks_path(@user, filter: 'incomplete') do %>
            <li class="task-filter <%= 'active' if @filter == 'incomplete' %>">Incomplete Tasks</li>
          <% end %>
          <%= link_to user_tasks_path(@user, filter: 'complete') do %>
            <li class="task-filter <%= 'active' if @filter == 'complete' %>">Complete Tasks</li>
          <% end %>
          <%= link_to user_tasks_path(@user, filter: 'all') do %>
            <li class="task-filter <%= 'active' if @filter == 'all' %>">All Tasks</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <% if List.count > 0 %>
      <div class="row">
        <div class="col-sm-12">
          <div class="add-btn-wrapper">
            <%= button_tag data: { toggle: 'modal', target: '#task-form-modal' }, class: 'add-task-btn btn btn-secondary' do %>
              <span class="glyphicon glyphicon-plus"></span> <strong>Add Task</strong>
            <% end %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <ul id="task-container" data-filter=<%= @filter %>>
            <%= render @tasks %>
          </ul>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="col-sm-12 text-center">
          <h4>Please <%= link_to 'create new list', new_list_path %> to add tasks!</h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: 'tasks/assignment_form', locals: { task: @user.assigned_tasks.new } %>